name: Build Test

on: workflow_dispatch

jobs:
  check:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Test
        run: |
          fastlane custom_lane