name: Comment Command

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  detect_command:
    runs-on: self-hosted
    outputs:
      triggered: ${{ steps.check.outputs.triggered }}
      comment: ${{ steps.check.outputs.comment_body }}
    steps:
      - id: check
        uses: khan/pull-request-comment-trigger@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          trigger: "@willog-bot"

  run_command:
    runs-on: self-hosted
    needs: detect_command
    permissions:
      contents: read
      issues: read
      pull-requests: read
      actions: write
    if: ${{ needs.detect_command.outputs.triggered == 'true' }}
    steps:
      - id: comment-branch
        uses: xt0rted/pull-request-comment-branch@v2  
      - id: parse
        run: |
          {
            # Message format
            # @willog-bot <command> <arguments... divided by '/'>
            comment="${{ needs.detect_command.outputs.comment }}"
            message=`echo ${comment#\$} | sed -e 's/^[[:space:]]*//'`
            
            echo "Command parsed: $message"

            tokens=($(tr " " "\n" <<< $message))
            
            command=${tokens[1]}
            arguments=$(tr "/" " " <<< ${tokens[2]})

            echo "command=$command" >> "$GITHUB_OUTPUT"
            echo "arguments=$arguments" >> "$GITHUB_OUTPUT"
          }
      - id: run
        run: |
          {
            command=${{ steps.parse.outputs.command }}
            arguments=($(tr " " "\n" <<< "${{ steps.parse.outputs.arguments }}"))
            
            case $command in
            deploy_feature)
              echo "workflow=deploy_feature.yml" >> "$GITHUB_OUTPUT"
              echo "inputs={\"target\": \"${arguments[0]}\", \"version\": \"${arguments[1]}\", \"build\": \"${arguments[2]}\", \"tag\": \"${arguments[3]}\"}" >> "$GITHUB_OUTPUT"
              ;;
            deploy)
            echo "workflow=deploy" >> "$GITHUB_OUTPUT"
            echo "inputs={\"type\": \"${arguments[0]}\", \"target\": \"${arguments[1]}\", \"version\": \"${arguments[2]}\", \"build\": \"${arguments[3]}\"}" >> "$GITHUB_OUTPUT"
              ;;
            build_check)
            echo "workflow=build_test.yml" >> "$GITHUB_OUTPUT"
              ;;
            esac
          }
      - id: trigger_workflow
        uses: benc-uk/workflow-dispatch@v1.2.2
        with: 
          workflow: ${{ steps.run.outputs.workflow }}
          ref: ${{ steps.comment-branch.outputs.head_ref }}
          inputs: ${{ steps.run.outputs.inputs }}