name: Comment Command

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  detect_command:
    runs-on: self-hosted
    outputs:
      triggered: ${{ steps.check.outputs.triggered }}
      comment: ${{ steps.check.outputs.comment_body }}
    steps:
      - id: check
        uses: khan/pull-request-comment-trigger@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          trigger: "@willog-bot"

  run_command:
    runs-on: self-hosted
    needs: detect_command
    permissions:
      pull-requests: write
    if: ${{ needs.detect_command.outputs.triggered == 'true' }}
    steps:
      - id: parse
        run: |
          {
            # Message format
            # @willog-bot <command> <arguments... divided by '/'>
            comment="${{ needs.detect_command.outputs.comment }}"
            message=`echo ${comment#\$} | sed -e 's/^[[:space:]]*//'`
            
            echo "Command parsed: $message"

            tokens=($(tr " " "\n" <<< $message))
            
            command=${tokens[1]}
            arguments=$(tr "/" " " <<< ${tokens[2]})

            echo "command=$command" >> "$GITHUB_OUTPUT"
            echo "arguments=$arguments" >> "$GITHUB_OUTPUT"
          }
      - id: run
        run: |
          {
            command=${{ steps.parse.outputs.command }}
            arguments=($(tr " " "\n" <<< ${{ steps.parse.outputs.arguments }}))
            
            echo $command
            echo ${arguments[0]}
            echo ${arguments[1]}
            echo ${arguments[2]}
            echo ${arguments[3]}
          }