name: Deploy Feature

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target to deploy (target scheme)'
        required: true
        type: string
      version:
        description: 'Version to deploy (major.minor.patch)'
        required: true
        type: string
      build:
        description: 'Build to deploy (number)'
        required: true
        type: number
      tag:
        description: 'Test scenario tag (feature name)'
        required: true
        type: string

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build & Deploy
        run: |
          fastlane feature target:${{ inputs.target }} version:${{ inputs.version }} build:${{ inputs.build }} tag:${{ inputs.tag }}