name: Deploy Feature

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target environment'
        required: true
        type: string
      version:
        description: 'Version to deploy'
        required: true
        type: string
      build:
        description: 'Build to deploy'
        required: true
        default: 'latest'
        type: number
      tags:
        description: 'Test scenario tag'
        required: true
        type: string

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build & Deploy
        run: |
          fastlane feature target:${{ inputs.target }} version:${{ inputs.version }} build:${{ inputs.build }} tags:${{ inputs.tags }}